version: "3"

services:

  nginx:
    container_name: nginx_rieutort
    image: nginx
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ./build:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - traefik.enable=true
      - traefik.backend=nginx_rieutort
      - traefik.docker.network=web
      # Port
      - traefik.http.services.nginx_rieutort.loadBalancer.server.port=80

      # Rule
      - traefik.http.routers.nginx_rieutort.rule=Host(`rieutort.jehanno.net`)
      # SSL configuration
      - traefik.http.routers.nginx_rieutort.entryPoints=websecure
      - traefik.http.routers.nginx_rieutort.tls=true
      - traefik.http.routers.nginx_rieutort.tls.certResolver=myresolver

networks:
  web:
    external: true